const Img = {
    notFound: require('./404.png'),

    accountGender_M: require('./account/gender_male_off.png'),
    accountGender_M_On: require('./account/gender_male_on.png'),
    accountGender_F: require('./account/gender_female_off.png'),
    accountGender_F_On: require('./account/gender_female_on.png'),
    accountSNS_naver: require('./account/sns_naver.png'),
    accountSNS_google: require('./account/sns_google.png'),
    accountSNS_apple: require('./account/sns_apple.png'),
    accountBg:require('./account/bg.jpg'),
    accountContactUs:require('./account/contact_us.png'),
    accountFaq:require('./account/faq.png'),

    commentExercise: require('./bodyComment/exercise.png'),
    commentStatus: require('./bodyComment/status.png'),
    commentFood: require('./bodyComment/food.png'),
    commentTypeFP: require('./bodyComment/somatoType.png'),
    commentFoodFP: require('./bodyComment/food_fitrus.png'),
    commentStressFP: require('./bodyComment/stress_fitrus.png'),
    commentWorkoutFP: require('./bodyComment/workout_fitrus.png'),

    analysisChart: require('./bodyComment/somato_chart.png'),
    analysisIcon_ecto: require('./bodyComment/ecto.png'),
    analysisIcon_endo: require('./bodyComment/endo.png'),
    analysisIcon_meso: require('./bodyComment/meso.png'),
    analysisComment: require('./bodyComment/talk4.png'),

    assistIcon_status: require('./bodyComment/body_smartdiet.png'),
    assistIcon_food: require('./bodyComment/food_smartdiet.png'),
    assistIcon_exercise: require('./bodyComment/workout_smartdiet.png'),

    arrow: require('./arrow-icon.png'),
    arrowGray: require('./arrow-icon_gray.png'),
    arrowTobe: require('./arrow_tobe.png'),

    barFoodAdd: require('./food/bar_add.png'),
    barSide: require('./bar/side.png'),
    barNoti: require('./bar/noti.png'),
    barConfirm: require('./bar/confirm.png'),

    bpmOxg: require('./bpm/oxg.png'),

    card_activity: require('./card/activity.png'),
    card_bodyFat: require('./card/bodyfat.png'),
    card_bodyType: require('./card/bodyType.png'),
    card_heart: require('./card/bpm.png'),
    card_food: require('./card/food.png'),
    card_stress: require('./card/stress.png'),
    card_temp: require('./card/temp.png'),
    card_tempObject: require('./card/temp_object.png'),
    card_tempSkin: require('./card/temp_skin.png'),
    card_goal: require('./card/goals.png'),
    card_weight: require('./card/weight.png'),
    card_mission: require('./card/mission.png'),
    card_ranking: require('./card/ranking.png'),
    card_group: require('./card/group.png'),
    card_noti: require('./card/noti.png'),

    comp_delete: require('./comp/delete.png'),
    comp_search: require('./comp/search.png'),

    challengeBanner: require('./challenge/banner.png'),
    challengeFounder: require('./challenge/founder.png'),
    challengeFriends: require('./challenge/friends.png'),
    challengeMedal1: require('./challenge/medal1.png'),
    challengeMedal2: require('./challenge/medal2.png'),
    challengeMedal3: require('./challenge/medal3.png'),
    challengeMedal4: require('./challenge/medal4.png'),
    challengeMedal5: require('./challenge/medal5.png'),
    challengeMember_green: require('./challenge/member_green.png'),
    challengeMember_lightGreen: require('./challenge/member_lightGreen.png'),
    challengeTop: require('./challenge/top.png'),
    challengeType_activity: require('./challenge/type_activity.png'),
    challengeType_activityOn: require('./challenge/type_activity_on.png'),
    challengeType_food: require('./challenge/type_food.png'),
    challengeType_foodOn: require('./challenge/type_food_on.png'),
    challengeX: require('./challenge/X.png'),
    challengeAddition: require('./challenge/addition.png'),
    challengeSubtraction: require('./challenge/subtraction.png'),

    checkbox: require('./checkbox.png'),
    checkboxNon: require('./checkbox_non.png'),

    dashboardBFP: require('./dashboard/BFP.png'),
    dashboardBMI: require('./dashboard/BMI.png'),
    dashboardSMM: require('./dashboard/SMM.png'),

    dateNext: require('./date_next.png'),
    dateNextOff: require('./date_next_off.png'),
    datePrev: require('./date_prev.png'),
    datePrevOff: require('./date_prev_off.png'),

    defaultProfile: require('./default_profile.png'),
    more: require('./more.png'),
    signupProfile: require('./account/profile.jpg'),
    profileArrow: require('./arrow-icon.png'),

    mail: require('./mail.png'),
    telephone: require('./telephone.png'),
    address: require('./address.png'),

    emptyDefault: require('./empty.png'),
    emptyFood: require('./food/empty.png'),

    fitrusPlus: require('./device/fitrusPlus.png'),
    smartDiet: require('./device/smartDiet.png'),

    foodBtnAdd: require('./food/btn_add.png'),
    foodBtnCheck: require('./food/btn_check.png'),
    foodBtnMinus: require('./food/btn_minus.png'),
    foodBtnPlus: require('./food/btn_plus.png'),
    foodCheck: require('./food/check.png'),
    foodDetailEmpty: require('./food/detail_empty.png'),
    food_breakfast: require('./food/breakfast_default.png'),
    food_breakfastOver: require('./food/breakfast_over.png'),
    food_breakfastPut: require('./food/breakfast_put.png'),
    food_dinner: require('./food/dinner_default.png'),
    food_dinnerOver: require('./food/dinner_over.png'),
    food_dinnerPut: require('./food/dinner_put.png'),
    food_lunch: require('./food/lunch_default.png'),
    food_lunchOver: require('./food/lunch_over.png'),
    food_lunchPut: require('./food/lunch_put.png'),
    food_snack: require('./food/snack_default.png'),
    food_snackOver: require('./food/snack_over.png'),
    food_snackPut: require('./food/snack_put.png'),

    goal: require('./goal.png'),
    goalActivity: require('./goal_activity.png'),
    goalTrophy: require('./goal_trophy.png'),

    guestBody: require('./guest/comp.png'),
    guestBpm: require('./guest/ppg.png'),
    guestTemp: require('./guest/temp.png'),
    guestTempObj: require('./guest/temp_object.png'),

    heart_status_normal_on: require('./bpm/normal_on.png'),
    heart_status_normal_off: require('./bpm/normal_off.png'),
    heart_status_stability_on: require('./bpm/stability_on.png'),
    heart_status_stability_off: require('./bpm/stability_off.png'),
    heart_status_before_exercise_on: require('./bpm/before_exercise_on.png'),
    heart_status_before_exercise_off: require('./bpm/before_exercise_off.png'),
    heart_status_after_running_on: require('./bpm/after_running_on.png'),
    heart_status_after_running_off: require('./bpm/after_running_off.png'),
    heart_status_after_walking_on: require('./bpm/after_walking_on.png'),
    heart_status_after_walking_off: require('./bpm/after_walking_off.png'),

    stress_status_normal_on: require('./stress/straight_face_on.png'),
    stress_status_normal_off: require('./stress/straight_face_off.png'),
    stress_status_angry_on: require('./stress/angry_face_on.png'),
    stress_status_angry_off: require('./stress/angry_face_off.png'),
    stress_status_pleasure_on: require('./stress/pleasure_face_on.png'),
    stress_status_pleasure_off: require('./stress/pleasure_face_off.png'),
    stress_status_sadness_on: require('./stress/sadness_face_on.png'),
    stress_status_sadness_off: require('./stress/sadness_face_off.png'),
    stress_status_surprise_on: require('./stress/surprise_face_on.png'),
    stress_status_surprise_off: require('./stress/surprise_face_off.png'),

    logo: require('./logo.png'),
    fitrusLogo: require('./signature.png'),
    defaultLogo: require('./defaultLogo.png'),

    measureInfo: require('./measure/measureInfo.png'),
    measureEx1: require('./measure/measureEx1.png'),
    measureEx2: require('./measure/measureEx2.png'),
    measureEx3: require('./measure/measureEx3.png'),
    measureBpm: require('./measure/measureBpm.png'),
    measureObject: require('./measure/measureObject.png'),
    measureSkin: require('./measure/measureSkin.png'),
    measureFail: require('./measure/fail.png'),
    measuringM_on: require('./measure/measuring_man_on.png'),
    measuringM_off: require('./measure/measuring_man_off.png'),
    measuringF_on: require('./measure/measuring_women_on.png'),
    measuringF_off: require('./measure/measuring_women_off.png'),
    measureSkinTemp1 : require('./measure/skin_temperature_1.png'),
    measureSkinTemp2 : require('./measure/skin_temperature_2.png'),
    measureFinger1 : require('./measure/heart_rate_1.png'),
    measureFinger2 : require('./measure/heart_rate_2.png'),
    measureObjectTemp1 : require('./measure/object_temperature_1.png'),
    measureObjectTemp2 : require('./measure/object_temperature_2.png'),


    nav_viewMore: require('./navigation/view_more.png'),
    nav_homeOn: require('./navigation/home_on.png'),
    nav_homeOff: require('./navigation/home_off.png'),
    nav_settingOn: require('./navigation/setting_on.png'),
    nav_settingOff: require('./navigation/setting_off.png'),

    question_green: require('./question_green.png'),
    question_lightBlue: require('./question_lightBlue.png'),
    question_lightGreen: require('./question_lightGreen.png'),

    mission_banner: require('./mission/mission_banner.jpg'),
    mission_file: require('./mission/attached.png'),

    stress: require('./stress/stress.png'),

    typeApple: require('./body/body_apple.png'),
    typeBanana: require('./body/body_banana.png'),
    typePear: require('./body/body_pear.png'),
    typeStrength1: require('./body/strength_1.png'),
    typeStrength2: require('./body/strength_2.png'),
    typeStrength3: require('./body/strength_3.png'),

    bodyType101: require('./bodyType/body_type_m01.png'),
    bodyType102: require('./bodyType/body_type_m02.png'),
    bodyType103: require('./bodyType/body_type_m03.png'),
    bodyType104: require('./bodyType/body_type_m04.png'),
    bodyType105: require('./bodyType/body_type_m05.png'),
    bodyType106: require('./bodyType/body_type_m06.png'),
    bodyType107: require('./bodyType/body_type_m07.png'),
    bodyType108: require('./bodyType/body_type_m08.png'),
    bodyType109: require('./bodyType/body_type_m09.png'),
    bodyType110: require('./bodyType/body_type_m10.png'),
    bodyType111: require('./bodyType/body_type_m11.png'),
    bodyType112: require('./bodyType/body_type_m12.png'),
    bodyType113: require('./bodyType/body_type_m13.png'),
    bodyType114: require('./bodyType/body_type_m14.png'),
    bodyType115: require('./bodyType/body_type_m15.png'),
    bodyType116: require('./bodyType/body_type_m16.png'),
    bodyType117: require('./bodyType/body_type_m17.png'),
    bodyType118: require('./bodyType/body_type_m18.png'),

    bodyType201: require('./bodyType/body_type_fa01.png'),
    bodyType202: require('./bodyType/body_type_fa02.png'),
    bodyType203: require('./bodyType/body_type_fa03.png'),
    bodyType204: require('./bodyType/body_type_fa04.png'),
    bodyType205: require('./bodyType/body_type_fa05.png'),
    bodyType206: require('./bodyType/body_type_fa06.png'),
    bodyType207: require('./bodyType/body_type_fa07.png'),
    bodyType208: require('./bodyType/body_type_fa08.png'),
    bodyType209: require('./bodyType/body_type_fa09.png'),
    bodyType210: require('./bodyType/body_type_fa10.png'),
    bodyType211: require('./bodyType/body_type_fa11.png'),
    bodyType212: require('./bodyType/body_type_fa12.png'),
    bodyType213: require('./bodyType/body_type_fa13.png'),
    bodyType214: require('./bodyType/body_type_fa14.png'),
    bodyType215: require('./bodyType/body_type_fa15.png'),
    bodyType216: require('./bodyType/body_type_fa16.png'),
    bodyType217: require('./bodyType/body_type_fa17.png'),
    bodyType218: require('./bodyType/body_type_fa18.png'),

    bodyType301: require('./bodyType/body_type_fp01.png'),
    bodyType302: require('./bodyType/body_type_fp02.png'),
    bodyType303: require('./bodyType/body_type_fp03.png'),
    bodyType304: require('./bodyType/body_type_fp04.png'),
    bodyType305: require('./bodyType/body_type_fp05.png'),
    bodyType306: require('./bodyType/body_type_fp06.png'),
    bodyType307: require('./bodyType/body_type_fp07.png'),
    bodyType308: require('./bodyType/body_type_fp08.png'),
    bodyType309: require('./bodyType/body_type_fp09.png'),
    bodyType310: require('./bodyType/body_type_fp10.png'),
    bodyType311: require('./bodyType/body_type_fp11.png'),
    bodyType312: require('./bodyType/body_type_fp12.png'),
    bodyType313: require('./bodyType/body_type_fp13.png'),
    bodyType314: require('./bodyType/body_type_fp14.png'),
    bodyType315: require('./bodyType/body_type_fp15.png'),
    bodyType316: require('./bodyType/body_type_fp16.png'),
    bodyType317: require('./bodyType/body_type_fp17.png'),
    bodyType318: require('./bodyType/body_type_fp18.png'),

    bodyType401: require('./bodyType/body_type_fb01.png'),
    bodyType402: require('./bodyType/body_type_fb02.png'),
    bodyType403: require('./bodyType/body_type_fb03.png'),
    bodyType404: require('./bodyType/body_type_fb04.png'),
    bodyType405: require('./bodyType/body_type_fb05.png'),
    bodyType406: require('./bodyType/body_type_fb06.png'),
    bodyType407: require('./bodyType/body_type_fb07.png'),
    bodyType408: require('./bodyType/body_type_fb08.png'),
    bodyType409: require('./bodyType/body_type_fb09.png'),
    bodyType410: require('./bodyType/body_type_fb10.png'),
    bodyType411: require('./bodyType/body_type_fb11.png'),
    bodyType412: require('./bodyType/body_type_fb12.png'),
    bodyType413: require('./bodyType/body_type_fb13.png'),
    bodyType414: require('./bodyType/body_type_fb14.png'),
    bodyType415: require('./bodyType/body_type_fb15.png'),
    bodyType416: require('./bodyType/body_type_fb16.png'),
    bodyType417: require('./bodyType/body_type_fb17.png'),
    bodyType418: require('./bodyType/body_type_fb18.png'),
};
export default Img
